<?php
$accesorios = [
	[
		'id_noticia' => 1,
		'titulo'     => 'Cinta',
		'texto'      => 'Reforzadas en distintos grosores',
		'imagen'     => 'accesorio_1.jpg',
		'imagen-alt' => 'accesorio de cinta',
	],
	[
		'id_noticia' => 2,
		'titulo'     => 'Enrrollador',
		'texto'      => 'Modelos: n°4,n°6,n°8 y especiales.',
		'imagen'     => 'accesorio_2.jpg',
		'imagen-alt' => 'accesorio enrrollador',
	],
	[
		'id_noticia' => 3,
		'titulo'     => 'Sistema manivela',
		'texto'      => 'Modelos T1, T2, T3',
		'imagen'     => 'accesorio_3.jpg',
		'imagen-alt' => 'Sistema manivela',
	],
	[
		'id_noticia' => 4,
		'titulo'     => 'Reductor de peso',
		'texto'      => 'De hierro - Modelos 1-3 y 1-4',
		'imagen'     => 'accesorio_4.jpg',
		'imagen-alt' => 'Reductor de peso',
	],
	[
		'id_noticia' => 5,
		'titulo'     => 'Tacos de PVC',
		'texto'      => '0.70mm y 0.60mm',
		'imagen'     => 'accesorio_5.jpg',
		'imagen-alt' => 'Tacos de pvc',
	],
	[
		'id_noticia' => 6,
		'titulo'     => 'Polea Galbanizada',
		'texto'      => 'Modelos n°20,23 y 26',
		'imagen'     => 'accesorio_6.jpg',
		'imagen-alt' => 'Polea galbanizada',
	],
	[
		'id_noticia' => 7,
		'titulo'     => 'Reductor Doble de Peso',
		'texto'      => 'De Hierro - Modelos 1-3 y 4-5',
		'imagen'     => 'accesorio_7.jpg',
		'imagen-alt' => 'Reductor doble de peso',
	],
	[
		'id_noticia' => 8,
		'titulo'     => 'Polea Doble Estabilizadora',
		'texto'      => 'De Hierro - Modelos n°20 y 23',
		'imagen'     => 'accesorio_8.jpg',
		'imagen-alt' => 'Polea doble estabilizadora',
	],
	[
		'id_noticia' => 9,
		'titulo'     => 'Corazones de PVC',
		'texto'      => 'Modelos octogonales',
		'imagen'     => 'accesorio_9.jpg',
		'imagen-alt' => 'Corazones de pvc',
	],
	[
		'id_noticia' => 10,
		'titulo'     => 'Eje Galbanizado',
		'texto'      => 'De Hierro , Modelos 0.60mm y 0.70mm',
		'imagen'     => 'accesorio_10.jpg',
		'imagen-alt' => 'Eje galbanizado',
	],
	[
		'id_noticia' => 11,
		'titulo'     => 'Ganchos de Hierro',
		'texto'      => 'Para cortinas de madera barriot',
		'imagen'     => 'accesorio_11.jpg',
		'imagen-alt' => 'Ganchos de hierro',
	],
	[
		'id_noticia' => 12,
		'titulo'     => 'Topes de PVC',
		'texto'      => 'Para cortinas de enrollar',
		'imagen'     => 'accesorio_12.jpg',
		'imagen-alt' => 'Topes de pvc',
	],
];